# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('recv_name', models.CharField(max_length=100, verbose_name='收货人')),
                ('recv_address', models.CharField(max_length=100, verbose_name='收货地址')),
                ('recv_phone', models.CharField(max_length=100, verbose_name='联系方式')),
                ('remark', models.CharField(max_length=255, verbose_name='备注信息')),
                ('all_price', models.FloatField(verbose_name='总计金额')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='订单所属用户')),
            ],
        ),
        migrations.CreateModel(
            name='OderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods_id', models.IntegerField(verbose_name='商品编号')),
                ('goods_img', models.CharField(max_length=100, verbose_name='商品图片')),
                ('goods_name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('goods_price', models.FloatField(verbose_name='商品单价')),
                ('goods_count', models.FloatField(verbose_name='商品数量')),
                ('goods_price_all', models.FloatField(verbose_name='商品总价')),
                ('oder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Oder', verbose_name='所属订单')),
            ],
        ),
    ]
