# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-19 07:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recv_name', models.CharField(max_length=100, verbose_name='收货人姓名')),
                ('recv_phone', models.CharField(max_length=20, verbose_name='收货人联系方式')),
                ('provice', models.CharField(max_length=100, verbose_name='收货人省区')),
                ('desc', models.CharField(max_length=100, verbose_name='详细描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认地址')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='地址所属用户')),
            ],
        ),
    ]
